/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hotel;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ltf
 */
public class panel_awal extends javax.swing.JFrame {

    /**
     * Creates new form panel_awal
     */
    panel_kamar pk;
    public panel_awal() throws SQLException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jComboBox1 = new javax.swing.JComboBox();
        jFrame1 = new javax.swing.JFrame();
        label_cek_in = new javax.swing.JLabel();
        button_new = new javax.swing.JButton();
        button_cek_kamar = new javax.swing.JButton();
        label_check_out = new javax.swing.JLabel();
        button_check_out = new javax.swing.JButton();
        button_member1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        label_cek_in.setBackground(new java.awt.Color(51, 204, 255));
        label_cek_in.setFont(new java.awt.Font("Sylfaen", 2, 24)); // NOI18N
        label_cek_in.setForeground(new java.awt.Color(51, 0, 204));
        label_cek_in.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_cek_in.setText("Check In");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(70, 400, 0, 0);
        getContentPane().add(label_cek_in, gridBagConstraints);

        button_new.setBackground(new java.awt.Color(153, 255, 51));
        button_new.setFont(new java.awt.Font("Sylfaen", 2, 24)); // NOI18N
        button_new.setText("New");
        button_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_newActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 34;
        gridBagConstraints.ipady = -7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 470, 0, 0);
        getContentPane().add(button_new, gridBagConstraints);

        button_cek_kamar.setBackground(new java.awt.Color(0, 204, 51));
        button_cek_kamar.setFont(new java.awt.Font("Sylfaen", 2, 24)); // NOI18N
        button_cek_kamar.setText("Cek Kamar");
        button_cek_kamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cek_kamarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = -7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(100, 450, 0, 0);
        getContentPane().add(button_cek_kamar, gridBagConstraints);

        label_check_out.setFont(new java.awt.Font("Sylfaen", 2, 24)); // NOI18N
        label_check_out.setForeground(new java.awt.Color(255, 51, 51));
        label_check_out.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_check_out.setText("Check Out");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 480, 0, 0);
        getContentPane().add(label_check_out, gridBagConstraints);

        button_check_out.setBackground(new java.awt.Color(102, 51, 255));
        button_check_out.setFont(new java.awt.Font("Sylfaen", 2, 24)); // NOI18N
        button_check_out.setText("Check Out");
        button_check_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_check_outActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(66, 460, 0, 0);
        getContentPane().add(button_check_out, gridBagConstraints);

        button_member1.setBackground(new java.awt.Color(0, 204, 51));
        button_member1.setFont(new java.awt.Font("Sylfaen", 2, 24)); // NOI18N
        button_member1.setText("Member");
        button_member1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_member1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.ipady = -7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 450, 0, 0);
        getContentPane().add(button_member1, gridBagConstraints);

        background.setBackground(new java.awt.Color(255, 0, 51));
        background.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        background.setForeground(new java.awt.Color(0, 51, 255));
        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel/Untitled-1.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.ipadx = -8;
        gridBagConstraints.ipady = -2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        getContentPane().add(background, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_newActionPerformed
        panel_new pn = new panel_new();
        pn.setVisible(true);
        
    }//GEN-LAST:event_button_newActionPerformed

    private void button_check_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_check_outActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_check_outActionPerformed

    private void button_cek_kamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cek_kamarActionPerformed
        try {
            pk = new panel_kamar();
        } catch (SQLException ex) {
            Logger.getLogger(panel_awal.class.getName()).log(Level.SEVERE, null, ex);
        }
        pk.setSize(430,600);
        pk.setVisible(true);
    }//GEN-LAST:event_button_cek_kamarActionPerformed

    private void button_member1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_member1ActionPerformed
        panel_member pm = new panel_member();
        pm.setVisible(true);
    }//GEN-LAST:event_button_member1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panel_awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panel_awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panel_awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panel_awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new panel_awal().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(panel_awal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton button_cek_kamar;
    private javax.swing.JButton button_check_out;
    private javax.swing.JButton button_member1;
    private javax.swing.JButton button_new;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel label_cek_in;
    private javax.swing.JLabel label_check_out;
    // End of variables declaration//GEN-END:variables
}
