/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;


/**
 *
 * @author Irfandi
 */
import Class.LoginEngine;
public class Login extends javax.swing.JFrame {
    LoginEngine LOG = new LoginEngine();
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        lbl_pesan.setVisible(false);
        System.out.println(LOG.liat());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_password = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        button_login = new javax.swing.JButton();
        lbl_lupapswd = new javax.swing.JLabel();
        lbl_pesan = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_password.setFont(new java.awt.Font("Bebas Neue", 0, 28)); // NOI18N
        lbl_password.setForeground(new java.awt.Color(255, 255, 255));
        lbl_password.setText("PASSWORD");
        getContentPane().add(lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 399, -1, 30));

        lbl_username.setFont(new java.awt.Font("Bebas Neue", 0, 28)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username.setText("USERNAME");
        getContentPane().add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 329, -1, 30));

        txt_username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 350, 40));

        txt_password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 350, 40));

        button_login.setBackground(new java.awt.Color(0, 153, 204));
        button_login.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button_login.setForeground(new java.awt.Color(153, 153, 153));
        button_login.setText("LOGIN");
        button_login.setOpaque(false);
        button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_loginActionPerformed(evt);
            }
        });
        getContentPane().add(button_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 210, 40));

        lbl_lupapswd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_lupapswd.setForeground(new java.awt.Color(0, 153, 255));
        lbl_lupapswd.setText("Lupa password ?");
        lbl_lupapswd.setToolTipText("Gunakan fungsi ini apabila anda tidak bisa mengakses akun anda");
        getContentPane().add(lbl_lupapswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 120, 20));

        lbl_pesan.setBackground(new java.awt.Color(255, 255, 255));
        lbl_pesan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_pesan.setForeground(new java.awt.Color(255, 0, 51));
        lbl_pesan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_pesan.setText("Username yang anda masukkan salah");
        getContentPane().add(lbl_pesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 380, 40));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BG LOGIN.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loginActionPerformed
        if (txt_username.getText().equals("")){
            SHOW_INFO("Username masih kosong");
        } else if (txt_password.getText().equals("")) {
           SHOW_INFO("Password kosong");
        } else {
            if ((LOG.LOGIN(txt_username.getText(), txt_password.getText())) == true) {
               SHOW_INFO("Username / Password benar");
            } else {
               SHOW_INFO("Username / Password salah");
            }
        }
    }//GEN-LAST:event_button_loginActionPerformed

    private void SHOW_INFO(String info){
        lbl_pesan.setText(info);
        lbl_pesan.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton button_login;
    private javax.swing.JLabel lbl_lupapswd;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_pesan;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
