/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Class.*;

/**
 *
 * @author Irfandi
 */
public class Main extends javax.swing.JFrame {
    Thread UPDATE_TIME;
    DateAndTime dt = new DateAndTime();
    UserEngine user = new UserEngine();
    KamarEngine kamar = new KamarEngine();
    
    class GET_TIME implements Runnable {

        public void run() {
            try {
                for (int x = 0;; x++) {
                    lbl_jam.setText(dt.GET_CURRENT_TIME("H:M"));
                    Thread.sleep(1000);
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        INIT_DATA();
        UPDATE_TIME = new Thread(new GET_TIME());
        UPDATE_TIME.start();
        System.out.println(user.liat());
        System.out.println(kamar.liat());
    }

    public void INIT_DATA() {
        int jumlah_pelanggan = user.GET_JUMLAH_USER();
        int total_kamar_tersedia = kamar.GET_TOTAL_KAMAR_TERSEDIA();
        int total_kamar_dipesan = kamar.GET_TOTAL_KAMAR_DIPESAN();
        int reg_kosong = kamar.GET_REG_KOSONG();
        int reg_dipesan = kamar.GET_REG_DIPESAN();
        int pre_kosong = kamar.GET_PRE_KOSONG();
        int pre_dipesan = kamar.GET_PRE_DIPESAN();
        int sui_kosong = kamar.GET_SUI_KOSONG();
        int sui_dipesan = kamar.GET_SUI_DIPESAN();
        int vip_kosong = kamar.GET_VIP_KOSONG();
        int vip_dipesan = kamar.GET_VIP_DIPESAN();
        
        JUMLAH_REG_TERSEDIA.setText(reg_kosong+ " Kamar Reguler Tersedia");
        JUMLAH_REG_DIPESAN.setText(reg_dipesan+ " Kamar Reguler Dipesan");
        JUMLAH_PRE_TERSEDIA.setText(pre_kosong+" Kamar Premium Tersedia");
        JUMLAH_PRE_DIPESAN.setText(pre_dipesan+" Kamar Premium Dipesan");
        JUMLAH_SUI_TERSEDIA.setText(sui_kosong+" Kamar Suite Tersedia");
        JUMLAH_SUI_DIPESAN.setText(sui_dipesan+" Kamar Suite Dipesan");
        JUMLAH_VIP_TERSEDIA.setText(vip_kosong+" Kamar VIP Tersedia");
        JUMLAH_VIP_DIPESAN.setText(vip_dipesan+" Kamar VIP Dipesan");
        JUMLAH_KAMAR_DIPESAN.setText(total_kamar_dipesan+" Kamar Dipesan");
        JUMLAH_KAMAR_TERSEDIA.setText(total_kamar_tersedia+" Kamar Tersedia");
        JUMLAH_PELANGGAN.setText(jumlah_pelanggan + " Pelanggan");
        lbl_tanggal.setText(dt.GET_CURRENT_DATE("D-M-Y"));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_beranda = new javax.swing.JLabel();
        icon_plus = new javax.swing.JLabel();
        icon_plus1 = new javax.swing.JLabel();
        icon_plus2 = new javax.swing.JLabel();
        icon_plus3 = new javax.swing.JLabel();
        menu_transaksi = new javax.swing.JLabel();
        menu_pelanggan = new javax.swing.JLabel();
        menu_keuangan = new javax.swing.JLabel();
        icon_beranda = new javax.swing.JLabel();
        icon_transaksi = new javax.swing.JLabel();
        icon_pelanggan = new javax.swing.JLabel();
        icon_keuangan = new javax.swing.JLabel();
        highlight = new javax.swing.JLabel();
        PANEL_BERANDA_OVERVIEW = new javax.swing.JLayeredPane();
        lbl_jam = new javax.swing.JLabel();
        lbl_tanggal = new javax.swing.JLabel();
        JUMLAH_PELANGGAN = new javax.swing.JLabel();
        JUMLAH_KAMAR_TERSEDIA = new javax.swing.JLabel();
        JUMLAH_KAMAR_DIPESAN = new javax.swing.JLabel();
        JUMLAH_REG_TERSEDIA = new javax.swing.JLabel();
        JUMLAH_REG_DIPESAN = new javax.swing.JLabel();
        JUMLAH_PRE_TERSEDIA = new javax.swing.JLabel();
        JUMLAH_PRE_DIPESAN = new javax.swing.JLabel();
        JUMLAH_SUI_TERSEDIA = new javax.swing.JLabel();
        JUMLAH_SUI_DIPESAN = new javax.swing.JLabel();
        JUMLAH_VIP_TERSEDIA = new javax.swing.JLabel();
        JUMLAH_VIP_DIPESAN = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu_beranda.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        menu_beranda.setForeground(new java.awt.Color(255, 255, 255));
        menu_beranda.setText("Beranda");
        menu_beranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_berandaMouseClicked(evt);
            }
        });
        getContentPane().add(menu_beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 120, -1, -1));

        icon_plus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus.png"))); // NOI18N
        getContentPane().add(icon_plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 122, -1, -1));

        icon_plus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus.png"))); // NOI18N
        getContentPane().add(icon_plus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 192, -1, -1));

        icon_plus2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus.png"))); // NOI18N
        getContentPane().add(icon_plus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 262, -1, -1));

        icon_plus3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus.png"))); // NOI18N
        getContentPane().add(icon_plus3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 332, -1, -1));

        menu_transaksi.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        menu_transaksi.setForeground(new java.awt.Color(255, 255, 255));
        menu_transaksi.setText("Transaksi");
        menu_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_transaksiMouseClicked(evt);
            }
        });
        getContentPane().add(menu_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 190, -1, -1));

        menu_pelanggan.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        menu_pelanggan.setForeground(new java.awt.Color(255, 255, 255));
        menu_pelanggan.setText("Pelanggan");
        menu_pelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_pelangganMouseClicked(evt);
            }
        });
        getContentPane().add(menu_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 260, -1, -1));

        menu_keuangan.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        menu_keuangan.setForeground(new java.awt.Color(255, 255, 255));
        menu_keuangan.setText("Keuangan");
        menu_keuangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_keuanganMouseClicked(evt);
            }
        });
        getContentPane().add(menu_keuangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 330, -1, -1));

        icon_beranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/beranda.png"))); // NOI18N
        getContentPane().add(icon_beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 122, -1, -1));

        icon_transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/transaksi.png"))); // NOI18N
        getContentPane().add(icon_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 192, -1, -1));

        icon_pelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pelanggan.png"))); // NOI18N
        getContentPane().add(icon_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 262, -1, -1));

        icon_keuangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/keuangan.png"))); // NOI18N
        getContentPane().add(icon_keuangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 332, -1, -1));

        highlight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form/selected.png"))); // NOI18N
        getContentPane().add(highlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 100, 280, 70));

        PANEL_BERANDA_OVERVIEW.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_jam.setFont(new java.awt.Font("Segoe UI Light", 0, 72)); // NOI18N
        lbl_jam.setText("23:59");
        PANEL_BERANDA_OVERVIEW.add(lbl_jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(825, 0, -1, -1));

        lbl_tanggal.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        lbl_tanggal.setText("15 Mei 2016");
        PANEL_BERANDA_OVERVIEW.add(lbl_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 83, -1, -1));

        JUMLAH_PELANGGAN.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        JUMLAH_PELANGGAN.setText("99 Pelanggan Terdaftar");
        PANEL_BERANDA_OVERVIEW.add(JUMLAH_PELANGGAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        JUMLAH_KAMAR_TERSEDIA.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        JUMLAH_KAMAR_TERSEDIA.setText("100 Kamar Tersedia");
        PANEL_BERANDA_OVERVIEW.add(JUMLAH_KAMAR_TERSEDIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        JUMLAH_KAMAR_DIPESAN.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        JUMLAH_KAMAR_DIPESAN.setText("100 Kamar Dipesan");
        PANEL_BERANDA_OVERVIEW.add(JUMLAH_KAMAR_DIPESAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        JUMLAH_REG_TERSEDIA.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        JUMLAH_REG_TERSEDIA.setText("100 Kamar Reguler Tersedia");
        PANEL_BERANDA_OVERVIEW.add(JUMLAH_REG_TERSEDIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        JUMLAH_REG_DIPESAN.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        JUMLAH_REG_DIPESAN.setText("100 Kamar Reguler Dipesan");
        PANEL_BERANDA_OVERVIEW.add(JUMLAH_REG_DIPESAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        JUMLAH_PRE_TERSEDIA.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        JUMLAH_PRE_TERSEDIA.setText("100 Kamar Premium Tersedia");
        PANEL_BERANDA_OVERVIEW.add(JUMLAH_PRE_TERSEDIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        JUMLAH_PRE_DIPESAN.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        JUMLAH_PRE_DIPESAN.setText("100 Kamar Premium Dipesan");
        PANEL_BERANDA_OVERVIEW.add(JUMLAH_PRE_DIPESAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        JUMLAH_SUI_TERSEDIA.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        JUMLAH_SUI_TERSEDIA.setText("100 Kamar Suite Tersedia");
        PANEL_BERANDA_OVERVIEW.add(JUMLAH_SUI_TERSEDIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        JUMLAH_SUI_DIPESAN.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        JUMLAH_SUI_DIPESAN.setText("100 Kamar Suite Dipesan");
        PANEL_BERANDA_OVERVIEW.add(JUMLAH_SUI_DIPESAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        JUMLAH_VIP_TERSEDIA.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        JUMLAH_VIP_TERSEDIA.setText("100 Kamar VIP Tersedia");
        PANEL_BERANDA_OVERVIEW.add(JUMLAH_VIP_TERSEDIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, -1, -1));

        JUMLAH_VIP_DIPESAN.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        JUMLAH_VIP_DIPESAN.setText("100 Kamar VIP Dipesan");
        PANEL_BERANDA_OVERVIEW.add(JUMLAH_VIP_DIPESAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, -1, -1));

        getContentPane().add(PANEL_BERANDA_OVERVIEW, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 990, 550));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MAIN LAYOUT.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_transaksiMouseClicked
        highlight.setLocation(-4, 170);
    }//GEN-LAST:event_menu_transaksiMouseClicked

    private void menu_berandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_berandaMouseClicked
        highlight.setLocation(-4, 100);
    }//GEN-LAST:event_menu_berandaMouseClicked

    private void menu_pelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_pelangganMouseClicked
        highlight.setLocation(-4, 240);
    }//GEN-LAST:event_menu_pelangganMouseClicked

    private void menu_keuanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_keuanganMouseClicked
        highlight.setLocation(-4, 310);
    }//GEN-LAST:event_menu_keuanganMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel JUMLAH_KAMAR_DIPESAN;
    private javax.swing.JLabel JUMLAH_KAMAR_TERSEDIA;
    private javax.swing.JLabel JUMLAH_PELANGGAN;
    private javax.swing.JLabel JUMLAH_PRE_DIPESAN;
    private javax.swing.JLabel JUMLAH_PRE_TERSEDIA;
    private javax.swing.JLabel JUMLAH_REG_DIPESAN;
    private javax.swing.JLabel JUMLAH_REG_TERSEDIA;
    private javax.swing.JLabel JUMLAH_SUI_DIPESAN;
    private javax.swing.JLabel JUMLAH_SUI_TERSEDIA;
    private javax.swing.JLabel JUMLAH_VIP_DIPESAN;
    private javax.swing.JLabel JUMLAH_VIP_TERSEDIA;
    private javax.swing.JLayeredPane PANEL_BERANDA_OVERVIEW;
    private javax.swing.JLabel highlight;
    private javax.swing.JLabel icon_beranda;
    private javax.swing.JLabel icon_keuangan;
    private javax.swing.JLabel icon_pelanggan;
    private javax.swing.JLabel icon_plus;
    private javax.swing.JLabel icon_plus1;
    private javax.swing.JLabel icon_plus2;
    private javax.swing.JLabel icon_plus3;
    private javax.swing.JLabel icon_transaksi;
    private javax.swing.JLabel lbl_jam;
    private javax.swing.JLabel lbl_tanggal;
    private javax.swing.JLabel menu_beranda;
    private javax.swing.JLabel menu_keuangan;
    private javax.swing.JLabel menu_pelanggan;
    private javax.swing.JLabel menu_transaksi;
    // End of variables declaration//GEN-END:variables
}
