/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Class.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Irfandi
 */
public class Main extends javax.swing.JFrame {
    Thread UPDATE_TIME;
    DateAndTime dt = new DateAndTime();
    UserEngine user = new UserEngine();
    KamarEngine kamar = new KamarEngine();
    TamuEngine tamu = new TamuEngine();
    
    class GET_TIME implements Runnable {

        public void run() {
            try {
                for (int x = 0;; x++) {
                    lbl_jam.setText(dt.GET_CURRENT_TIME("H:M"));
                    Thread.sleep(1000);
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        INIT_DATA();
        UPDATE_TIME = new Thread(new GET_TIME());
        UPDATE_TIME.start();
        PANEL_BERANDA_OVERVIEW.setVisible(true);
        PANEL_PELANGGAN_TAMU.setVisible(false);
        clear_highlight();
        highlight_beranda.setVisible(true);
        System.out.println(user.liat());
        System.out.println(kamar.liat());
        UPDATE_INFO(0);
    }

    public void INIT_DATA() {
        int jumlah_pelanggan = user.GET_JUMLAH_USER();
        int jumlah_tamu = tamu.GET_JUMLAH_TAMU();
        int total_kamar_tersedia = kamar.GET_TOTAL_KAMAR_TERSEDIA();
        int total_kamar_dipesan = kamar.GET_TOTAL_KAMAR_DIPESAN();
        int reg_kosong = kamar.GET_REG_KOSONG();
        int reg_dipesan = kamar.GET_REG_DIPESAN();
        int pre_kosong = kamar.GET_PRE_KOSONG();
        int pre_dipesan = kamar.GET_PRE_DIPESAN();
        int sui_kosong = kamar.GET_SUI_KOSONG();
        int sui_dipesan = kamar.GET_SUI_DIPESAN();
        int vip_kosong = kamar.GET_VIP_KOSONG();
        int vip_dipesan = kamar.GET_VIP_DIPESAN();
 
        JUMLAH_TAMU.setText(jumlah_tamu+ " Tamu Menginap");
        JUMLAH_REG_TERSEDIA.setText(reg_kosong+ " Kamar Reguler Tersedia");
        JUMLAH_REG_DIPESAN.setText(reg_dipesan+ " Kamar Reguler Dipesan");
        JUMLAH_PRE_TERSEDIA.setText(pre_kosong+" Kamar Premium Tersedia");
        JUMLAH_PRE_DIPESAN.setText(pre_dipesan+" Kamar Premium Dipesan");
        JUMLAH_SUI_TERSEDIA.setText(sui_kosong+" Kamar Suite Tersedia");
        JUMLAH_SUI_DIPESAN.setText(sui_dipesan+" Kamar Suite Dipesan");
        JUMLAH_VIP_TERSEDIA.setText(vip_kosong+" Kamar VIP Tersedia");
        JUMLAH_VIP_DIPESAN.setText(vip_dipesan+" Kamar VIP Dipesan");
        JUMLAH_KAMAR_DIPESAN.setText(total_kamar_dipesan+" Kamar Dipesan");
        JUMLAH_KAMAR_TERSEDIA.setText(total_kamar_tersedia+" Kamar Tersedia");
        JUMLAH_PELANGGAN.setText(jumlah_pelanggan + " Pelanggan");
        lbl_tanggal.setText(dt.GET_CURRENT_DATE("D-M-Y"));
        INIT_TABLE();
    }
    
    public void INIT_TABLE(){
        DefaultTableModel model = (DefaultTableModel) TABLE_TAMU.getModel();
        
        for (int i = 0; i < tamu.GET_JUMLAH_TAMU(); i++) {
            String ID = tamu.GET_ID_BY_INDEX(i);
            String NIK = tamu.GET_NIK_BY_INDEX(i);
            String NAMA = tamu.GET_NAMA_BY_INDEX(i);
            String KAMAR = tamu.GET_KAMAR_BY_INDEX(i);
            String CHK_IN = tamu.GET_STRING_CHECK_IN_BY_INDEX(i);
            String CHK_OUT = tamu.GET_STRING_CHECK_OUT_BY_INDEX(i);
            String[] tamu_ = {ID, NIK, NAMA, KAMAR, CHK_IN, CHK_OUT};
            model.addRow(tamu_);
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_beranda = new javax.swing.JLabel();
        icon_plus = new javax.swing.JLabel();
        icon_plus1 = new javax.swing.JLabel();
        icon_plus2 = new javax.swing.JLabel();
        icon_plus3 = new javax.swing.JLabel();
        menu_transaksi = new javax.swing.JLabel();
        menu_pelanggan = new javax.swing.JLabel();
        menu_keuangan = new javax.swing.JLabel();
        icon_beranda = new javax.swing.JLabel();
        icon_transaksi = new javax.swing.JLabel();
        icon_pelanggan = new javax.swing.JLabel();
        icon_keuangan = new javax.swing.JLabel();
        highlight_beranda = new javax.swing.JLabel();
        highlight_transaksi = new javax.swing.JLabel();
        highlight_pelanggan = new javax.swing.JLabel();
        highlight_keuangan = new javax.swing.JLabel();
        PANEL_PELANGGAN_TAMU = new javax.swing.JLayeredPane();
        lbl_ID_tamu = new javax.swing.JLabel();
        lbl_nama_tamu = new javax.swing.JLabel();
        lbl_nik_tamu = new javax.swing.JLabel();
        lbl_kamar_tamu = new javax.swing.JLabel();
        lbl_co_tamu = new javax.swing.JLabel();
        lbl_ci_tamu = new javax.swing.JLabel();
        lbl_diskon_tamu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLE_TAMU = new javax.swing.JTable();
        LABEL = new javax.swing.JLabel();
        LABEL1 = new javax.swing.JLabel();
        LABEL2 = new javax.swing.JLabel();
        LABEL3 = new javax.swing.JLabel();
        LABEL4 = new javax.swing.JLabel();
        LABEL5 = new javax.swing.JLabel();
        color1 = new javax.swing.JLabel();
        PANEL_BERANDA_OVERVIEW = new javax.swing.JLayeredPane();
        lbl_jam = new javax.swing.JLabel();
        lbl_tanggal = new javax.swing.JLabel();
        JUMLAH_PELANGGAN = new javax.swing.JLabel();
        JUMLAH_KAMAR_TERSEDIA = new javax.swing.JLabel();
        JUMLAH_KAMAR_DIPESAN = new javax.swing.JLabel();
        JUMLAH_REG_TERSEDIA = new javax.swing.JLabel();
        JUMLAH_REG_DIPESAN = new javax.swing.JLabel();
        JUMLAH_PRE_TERSEDIA = new javax.swing.JLabel();
        JUMLAH_PRE_DIPESAN = new javax.swing.JLabel();
        JUMLAH_SUI_TERSEDIA = new javax.swing.JLabel();
        JUMLAH_SUI_DIPESAN = new javax.swing.JLabel();
        JUMLAH_VIP_TERSEDIA = new javax.swing.JLabel();
        JUMLAH_VIP_DIPESAN = new javax.swing.JLabel();
        JUMLAH_TAMU = new javax.swing.JLabel();
        BG_REG = new javax.swing.JLabel();
        BG_SUITE = new javax.swing.JLabel();
        BG_VIP = new javax.swing.JLabel();
        BG_PRE1 = new javax.swing.JLabel();
        color = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu_beranda.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        menu_beranda.setForeground(new java.awt.Color(255, 255, 255));
        menu_beranda.setText("Beranda");
        menu_beranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_berandaMouseClicked(evt);
            }
        });
        getContentPane().add(menu_beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 120, -1, -1));

        icon_plus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus.png"))); // NOI18N
        getContentPane().add(icon_plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 122, -1, -1));

        icon_plus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus.png"))); // NOI18N
        getContentPane().add(icon_plus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 192, -1, -1));

        icon_plus2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus.png"))); // NOI18N
        getContentPane().add(icon_plus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 262, -1, -1));

        icon_plus3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus.png"))); // NOI18N
        getContentPane().add(icon_plus3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 332, -1, -1));

        menu_transaksi.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        menu_transaksi.setForeground(new java.awt.Color(255, 255, 255));
        menu_transaksi.setText("Transaksi");
        menu_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_transaksiMouseClicked(evt);
            }
        });
        getContentPane().add(menu_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 190, -1, -1));

        menu_pelanggan.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        menu_pelanggan.setForeground(new java.awt.Color(255, 255, 255));
        menu_pelanggan.setText("Pelanggan");
        menu_pelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_pelangganMouseClicked(evt);
            }
        });
        getContentPane().add(menu_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 260, -1, -1));

        menu_keuangan.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        menu_keuangan.setForeground(new java.awt.Color(255, 255, 255));
        menu_keuangan.setText("Keuangan");
        menu_keuangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_keuanganMouseClicked(evt);
            }
        });
        getContentPane().add(menu_keuangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 330, -1, -1));

        icon_beranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/beranda.png"))); // NOI18N
        getContentPane().add(icon_beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 122, -1, -1));

        icon_transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/transaksi.png"))); // NOI18N
        getContentPane().add(icon_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 192, -1, -1));

        icon_pelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pelanggan.png"))); // NOI18N
        getContentPane().add(icon_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 262, -1, -1));

        icon_keuangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/keuangan.png"))); // NOI18N
        getContentPane().add(icon_keuangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 332, -1, -1));

        highlight_beranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form/selected.png"))); // NOI18N
        getContentPane().add(highlight_beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 100, 280, 70));

        highlight_transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form/selected.png"))); // NOI18N
        getContentPane().add(highlight_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 170, 280, 70));

        highlight_pelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form/selected.png"))); // NOI18N
        getContentPane().add(highlight_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 240, 280, 70));

        highlight_keuangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form/selected.png"))); // NOI18N
        getContentPane().add(highlight_keuangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 310, 280, 70));

        PANEL_PELANGGAN_TAMU.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_ID_tamu.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lbl_ID_tamu.setText("RI123");
        PANEL_PELANGGAN_TAMU.add(lbl_ID_tamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        lbl_nama_tamu.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        lbl_nama_tamu.setText("Ricky Irfandi");
        PANEL_PELANGGAN_TAMU.add(lbl_nama_tamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        lbl_nik_tamu.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lbl_nik_tamu.setText("155150201111274");
        PANEL_PELANGGAN_TAMU.add(lbl_nik_tamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, -1, -1));

        lbl_kamar_tamu.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lbl_kamar_tamu.setText("099V");
        PANEL_PELANGGAN_TAMU.add(lbl_kamar_tamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, -1, -1));

        lbl_co_tamu.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lbl_co_tamu.setText("Senin, 5 Desember 2017");
        PANEL_PELANGGAN_TAMU.add(lbl_co_tamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, -1, -1));

        lbl_ci_tamu.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lbl_ci_tamu.setText("Minggu, 5 Januari 2015");
        PANEL_PELANGGAN_TAMU.add(lbl_ci_tamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, -1, -1));

        lbl_diskon_tamu.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lbl_diskon_tamu.setText("50 %");
        PANEL_PELANGGAN_TAMU.add(lbl_diskon_tamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, -1, -1));

        TABLE_TAMU.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TABLE_TAMU.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NIK", "Nama", "No Kamar", "Check In", "Check Out"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TABLE_TAMU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABLE_TAMUMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TABLE_TAMU);

        PANEL_PELANGGAN_TAMU.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 970, 280));

        LABEL.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        LABEL.setText("Kamar    : ");
        PANEL_PELANGGAN_TAMU.add(LABEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        LABEL1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        LABEL1.setText("Diskon         : ");
        PANEL_PELANGGAN_TAMU.add(LABEL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, -1, -1));

        LABEL2.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        LABEL2.setText("NIK        : ");
        PANEL_PELANGGAN_TAMU.add(LABEL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        LABEL3.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        LABEL3.setText("ID          : ");
        PANEL_PELANGGAN_TAMU.add(LABEL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        LABEL4.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        LABEL4.setText("Check In      : ");
        PANEL_PELANGGAN_TAMU.add(LABEL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, -1, -1));

        LABEL5.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        LABEL5.setText("Check Out   : ");
        PANEL_PELANGGAN_TAMU.add(LABEL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, -1, -1));

        color1.setBackground(new java.awt.Color(255, 255, 255));
        color1.setOpaque(true);
        PANEL_PELANGGAN_TAMU.add(color1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 550));

        getContentPane().add(PANEL_PELANGGAN_TAMU, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 1000, 550));

        PANEL_BERANDA_OVERVIEW.setBackground(new java.awt.Color(255, 255, 255));
        PANEL_BERANDA_OVERVIEW.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_jam.setFont(new java.awt.Font("Segoe UI Light", 0, 72)); // NOI18N
        lbl_jam.setText("23:59");
        PANEL_BERANDA_OVERVIEW.add(lbl_jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(825, 0, -1, -1));

        lbl_tanggal.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        lbl_tanggal.setText("15 Mei 2016");
        PANEL_BERANDA_OVERVIEW.add(lbl_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 83, -1, -1));

        JUMLAH_PELANGGAN.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        JUMLAH_PELANGGAN.setText("99 Pelanggan Terdaftar");
        PANEL_BERANDA_OVERVIEW.add(JUMLAH_PELANGGAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        JUMLAH_KAMAR_TERSEDIA.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        JUMLAH_KAMAR_TERSEDIA.setText("100 Kamar Tersedia");
        PANEL_BERANDA_OVERVIEW.add(JUMLAH_KAMAR_TERSEDIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        JUMLAH_KAMAR_DIPESAN.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        JUMLAH_KAMAR_DIPESAN.setText("100 Kamar Dipesan");
        PANEL_BERANDA_OVERVIEW.add(JUMLAH_KAMAR_DIPESAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        JUMLAH_REG_TERSEDIA.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        JUMLAH_REG_TERSEDIA.setForeground(new java.awt.Color(255, 255, 255));
        JUMLAH_REG_TERSEDIA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JUMLAH_REG_TERSEDIA.setText("100 Kamar Reguler Tersedia");
        PANEL_BERANDA_OVERVIEW.add(JUMLAH_REG_TERSEDIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 460, -1));

        JUMLAH_REG_DIPESAN.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        JUMLAH_REG_DIPESAN.setForeground(new java.awt.Color(255, 255, 255));
        JUMLAH_REG_DIPESAN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JUMLAH_REG_DIPESAN.setText("100 Kamar Reguler Dipesan");
        PANEL_BERANDA_OVERVIEW.add(JUMLAH_REG_DIPESAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 460, -1));

        JUMLAH_PRE_TERSEDIA.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        JUMLAH_PRE_TERSEDIA.setForeground(new java.awt.Color(255, 255, 255));
        JUMLAH_PRE_TERSEDIA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JUMLAH_PRE_TERSEDIA.setText("100 Kamar Premium Tersedia");
        PANEL_BERANDA_OVERVIEW.add(JUMLAH_PRE_TERSEDIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 460, -1));

        JUMLAH_PRE_DIPESAN.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        JUMLAH_PRE_DIPESAN.setForeground(new java.awt.Color(255, 255, 255));
        JUMLAH_PRE_DIPESAN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JUMLAH_PRE_DIPESAN.setText("100 Kamar Premium Dipesan");
        PANEL_BERANDA_OVERVIEW.add(JUMLAH_PRE_DIPESAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 460, -1));

        JUMLAH_SUI_TERSEDIA.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        JUMLAH_SUI_TERSEDIA.setForeground(new java.awt.Color(255, 255, 255));
        JUMLAH_SUI_TERSEDIA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JUMLAH_SUI_TERSEDIA.setText("100 Kamar Suite Tersedia");
        PANEL_BERANDA_OVERVIEW.add(JUMLAH_SUI_TERSEDIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 460, -1));

        JUMLAH_SUI_DIPESAN.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        JUMLAH_SUI_DIPESAN.setForeground(new java.awt.Color(255, 255, 255));
        JUMLAH_SUI_DIPESAN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JUMLAH_SUI_DIPESAN.setText("100 Kamar Suite Dipesan");
        PANEL_BERANDA_OVERVIEW.add(JUMLAH_SUI_DIPESAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 460, -1));

        JUMLAH_VIP_TERSEDIA.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        JUMLAH_VIP_TERSEDIA.setForeground(new java.awt.Color(255, 255, 255));
        JUMLAH_VIP_TERSEDIA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JUMLAH_VIP_TERSEDIA.setText("100 Kamar VIP Tersedia");
        PANEL_BERANDA_OVERVIEW.add(JUMLAH_VIP_TERSEDIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 450, -1));

        JUMLAH_VIP_DIPESAN.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        JUMLAH_VIP_DIPESAN.setForeground(new java.awt.Color(255, 255, 255));
        JUMLAH_VIP_DIPESAN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JUMLAH_VIP_DIPESAN.setText("100 Kamar VIP Dipesan");
        PANEL_BERANDA_OVERVIEW.add(JUMLAH_VIP_DIPESAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 450, -1));

        JUMLAH_TAMU.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        JUMLAH_TAMU.setText("99 Tamu Menginap");
        PANEL_BERANDA_OVERVIEW.add(JUMLAH_TAMU, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        BG_REG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/kamar_reguler.png"))); // NOI18N
        PANEL_BERANDA_OVERVIEW.add(BG_REG, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        BG_SUITE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/kamar_suite.png"))); // NOI18N
        PANEL_BERANDA_OVERVIEW.add(BG_SUITE, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, -1));

        BG_VIP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/kamar_vip.png"))); // NOI18N
        PANEL_BERANDA_OVERVIEW.add(BG_VIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, -1, -1));

        BG_PRE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/kamar_premium.png"))); // NOI18N
        PANEL_BERANDA_OVERVIEW.add(BG_PRE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        color.setBackground(new java.awt.Color(255, 255, 255));
        color.setOpaque(true);
        PANEL_BERANDA_OVERVIEW.add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 550));

        getContentPane().add(PANEL_BERANDA_OVERVIEW, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 990, 550));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MAIN LAYOUT.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void clear_highlight(){
    highlight_beranda.setVisible(false);
    highlight_transaksi.setVisible(false);
    highlight_pelanggan.setVisible(false);
    highlight_keuangan.setVisible(false);
}
    private void menu_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_transaksiMouseClicked
        clear_highlight();
        highlight_transaksi.setVisible(true);
    }//GEN-LAST:event_menu_transaksiMouseClicked

    private void menu_berandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_berandaMouseClicked
        clear_highlight();
        highlight_beranda.setVisible(true);
        PANEL_BERANDA_OVERVIEW.setVisible(true);
        PANEL_PELANGGAN_TAMU.setVisible(false);
    }//GEN-LAST:event_menu_berandaMouseClicked

    private void menu_pelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_pelangganMouseClicked
        clear_highlight();
        highlight_pelanggan.setVisible(true);
        PANEL_BERANDA_OVERVIEW.setVisible(false);
        PANEL_PELANGGAN_TAMU.setVisible(true);
    }//GEN-LAST:event_menu_pelangganMouseClicked

    private void menu_keuanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_keuanganMouseClicked
        clear_highlight();
        highlight_keuangan.setVisible(true);
    }//GEN-LAST:event_menu_keuanganMouseClicked

    private void TABLE_TAMUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLE_TAMUMouseClicked
        int row = TABLE_TAMU.getSelectedRow();
        int kolom = TABLE_TAMU.getSelectedColumn();
        System.out.println("row : "+row+", kolom : "+kolom+", value : "+TABLE_TAMU.getValueAt(row, kolom));
        UPDATE_INFO(row);
    }//GEN-LAST:event_TABLE_TAMUMouseClicked

    public void UPDATE_INFO(int index){
        lbl_nama_tamu.setText((String) TABLE_TAMU.getValueAt(index, 2));
        lbl_nik_tamu.setText((String) TABLE_TAMU.getValueAt(index, 1));
        lbl_ID_tamu.setText((String) TABLE_TAMU.getValueAt(index, 0));
        lbl_kamar_tamu.setText((String) TABLE_TAMU.getValueAt(index, 3));
        lbl_ci_tamu.setText((String) TABLE_TAMU.getValueAt(index, 4));
        lbl_co_tamu.setText((String) TABLE_TAMU.getValueAt(index, 5));
        lbl_diskon_tamu.setText(tamu.GET_DISKON_BY_INDEX(index));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG_PRE1;
    private javax.swing.JLabel BG_REG;
    private javax.swing.JLabel BG_SUITE;
    private javax.swing.JLabel BG_VIP;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel JUMLAH_KAMAR_DIPESAN;
    private javax.swing.JLabel JUMLAH_KAMAR_TERSEDIA;
    private javax.swing.JLabel JUMLAH_PELANGGAN;
    private javax.swing.JLabel JUMLAH_PRE_DIPESAN;
    private javax.swing.JLabel JUMLAH_PRE_TERSEDIA;
    private javax.swing.JLabel JUMLAH_REG_DIPESAN;
    private javax.swing.JLabel JUMLAH_REG_TERSEDIA;
    private javax.swing.JLabel JUMLAH_SUI_DIPESAN;
    private javax.swing.JLabel JUMLAH_SUI_TERSEDIA;
    private javax.swing.JLabel JUMLAH_TAMU;
    private javax.swing.JLabel JUMLAH_VIP_DIPESAN;
    private javax.swing.JLabel JUMLAH_VIP_TERSEDIA;
    private javax.swing.JLabel LABEL;
    private javax.swing.JLabel LABEL1;
    private javax.swing.JLabel LABEL2;
    private javax.swing.JLabel LABEL3;
    private javax.swing.JLabel LABEL4;
    private javax.swing.JLabel LABEL5;
    private javax.swing.JLayeredPane PANEL_BERANDA_OVERVIEW;
    private javax.swing.JLayeredPane PANEL_PELANGGAN_TAMU;
    private javax.swing.JTable TABLE_TAMU;
    private javax.swing.JLabel color;
    private javax.swing.JLabel color1;
    private javax.swing.JLabel highlight_beranda;
    private javax.swing.JLabel highlight_keuangan;
    private javax.swing.JLabel highlight_pelanggan;
    private javax.swing.JLabel highlight_transaksi;
    private javax.swing.JLabel icon_beranda;
    private javax.swing.JLabel icon_keuangan;
    private javax.swing.JLabel icon_pelanggan;
    private javax.swing.JLabel icon_plus;
    private javax.swing.JLabel icon_plus1;
    private javax.swing.JLabel icon_plus2;
    private javax.swing.JLabel icon_plus3;
    private javax.swing.JLabel icon_transaksi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_ID_tamu;
    private javax.swing.JLabel lbl_ci_tamu;
    private javax.swing.JLabel lbl_co_tamu;
    private javax.swing.JLabel lbl_diskon_tamu;
    private javax.swing.JLabel lbl_jam;
    private javax.swing.JLabel lbl_kamar_tamu;
    private javax.swing.JLabel lbl_nama_tamu;
    private javax.swing.JLabel lbl_nik_tamu;
    private javax.swing.JLabel lbl_tanggal;
    private javax.swing.JLabel menu_beranda;
    private javax.swing.JLabel menu_keuangan;
    private javax.swing.JLabel menu_pelanggan;
    private javax.swing.JLabel menu_transaksi;
    // End of variables declaration//GEN-END:variables
}
