/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

/**
 *
 * @author gunka
 */
public class OpenFrame extends javax.swing.JFrame {

    /**
     * Creates new form OpenFrame
     */
    public OpenFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelHotel = new javax.swing.JLabel();
        labelWelcome = new javax.swing.JLabel();
        gifLoad = new javax.swing.JLabel();
        BackgroundLoad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelHotel.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        labelHotel.setText("HOTEL MANTAP");
        getContentPane().add(labelHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 210, -1));

        labelWelcome.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        labelWelcome.setText("WELCOME TO");
        getContentPane().add(labelWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 180, -1));

        gifLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/491.gif"))); // NOI18N
        getContentPane().add(gifLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 260, 20));

        BackgroundLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Background Potong mini.jpg"))); // NOI18N
        getContentPane().add(BackgroundLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpenFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundLoad;
    private javax.swing.JLabel gifLoad;
    private javax.swing.JLabel labelHotel;
    private javax.swing.JLabel labelWelcome;
    // End of variables declaration//GEN-END:variables
}
